/* MongoDB data layer for N.F International. */
// Netlify's Node 18 Function runtime does not always expose Web Crypto globally.
// Mongoose uses it while generating ObjectIds, so provide Node's built-in implementation.
if (!globalThis.crypto) globalThis.crypto = require('crypto').webcrypto;
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const dns = require('dns');
const { Schema } = mongoose;
const options = { timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' }, versionKey: false };

const Admin = mongoose.model('Admin', new Schema({ username: { type: String, required: true, unique: true, trim: true }, password_hash: { type: String, required: true } }, options));
const Job = mongoose.model('Job', new Schema({ title: { type: String, required: true, trim: true }, category: { type: String, required: true }, country: { type: String, required: true, trim: true }, city: String, contract: String, benefits: String, salary: String, vacancies: { type: Number, default: 1, min: 1 }, active: { type: Boolean, default: true } }, options));
const Application = mongoose.model('Application', new Schema({ job_title: { type: String, default: 'General Application' }, applicant_name: { type: String, required: true, trim: true }, applicant_phone: { type: String, required: true, trim: true }, passport_status: String, experience: String }, { ...options, timestamps: { createdAt: 'submitted_at', updatedAt: false } }));
const Inquiry = mongoose.model('Inquiry', new Schema({ name: { type: String, required: true, trim: true }, email: String, phone: { type: String, required: true, trim: true }, message: { type: String, required: true, trim: true } }, { ...options, timestamps: { createdAt: 'submitted_at', updatedAt: false } }));
const Employee = mongoose.model('Employee', new Schema({ name: { type: String, required: true, trim: true }, role: { type: String, required: true, trim: true }, phone: String, email: String, status: { type: String, enum: ['active', 'inactive'], default: 'active' } }, options));

const seedJobs = [
  ['Senior Steel Fixer & Mason', 'construction', 'Saudi Arabia', 'Riyadh', '2 Years (Renewable)', 'Accommodation & Food Provided', '1,500 - 1,800 SAR', 25], ['Staff Nurse (Female)', 'healthcare', 'UAE', 'Dubai', '2 Years (DHA Approved)', 'Medical Insurance & Overtime', '4,500 - 6,000 AED', 10], ['HVAC Technician & Electrician', 'engineering', 'Qatar', 'Doha', '2 Years', '3+ Yrs Experience Required', '2,200 - 2,800 QAR', 8], ['Hotel Waiter & Kitchen Crew', 'hospitality', 'Malaysia', 'Kuala Lumpur', '3 Years', 'Duty Meals & Uniform', '1,800 - 2,200 MYR', 15], ['Heavy Trailer Driver', 'logistics', 'Oman', 'Muscat', '2 Years', 'GCC / Valid License Required', '250 - 320 OMR', 12], ['Pipe Fitter & Shuttering Carpenter', 'construction', 'Saudi Arabia', 'Jeddah', '2 Years', 'Complete PPE Included', '1,400 - 1,700 SAR', 30]
].map(([title, category, country, city, contract, benefits, salary, vacancies]) => ({ title, category, country, city, contract, benefits, salary, vacancies }));

async function connect() { if (mongoose.connection.readyState === 1) return; const uri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/nf_international'; const dnsServers = (process.env.DNS_SERVERS || '8.8.8.8,1.1.1.1').split(',').map(server => server.trim()).filter(Boolean); if (uri.startsWith('mongodb+srv://') && dnsServers.length) dns.setServers(dnsServers); await mongoose.connect(uri, { serverSelectionTimeoutMS: 15000 }); if (!await Admin.exists({ username: 'nfadmin' })) await Admin.create({ username: 'nfadmin', password_hash: await bcrypt.hash('mamun123', 10) }); if (await Job.countDocuments() === 0) await Job.insertMany(seedJobs); console.log(`✔ Connected to MongoDB database: ${mongoose.connection.name}`); }
function cleanJob(data) { return { title: data.title, category: data.category, country: data.country, city: data.city || '', contract: data.contract || '', benefits: data.benefits || '', salary: data.salary || '', vacancies: Number(data.vacancies) || 1, active: data.active === undefined ? true : Boolean(Number(data.active)) }; }
module.exports = { connect, getAdminByUsername: username => Admin.findOne({ username }).lean(), getAllJobs: () => Job.find().sort({ created_at: -1 }).lean(), createJob: data => Job.create(cleanJob(data)), updateJob: (id, data) => Job.findByIdAndUpdate(id, cleanJob(data), { new: true }).lean(), deleteJob: async id => Boolean(await Job.findByIdAndDelete(id)), getAllApplications: () => Application.find().sort({ submitted_at: -1 }).lean(), createApplication: data => Application.create({ job_title: data.job_title || 'General Application', applicant_name: data.applicant_name, applicant_phone: data.applicant_phone, passport_status: data.passport_status || '', experience: data.experience || '' }), deleteApplication: async id => Boolean(await Application.findByIdAndDelete(id)), getAllInquiries: () => Inquiry.find().sort({ submitted_at: -1 }).lean(), createInquiry: data => Inquiry.create({ name: data.name, email: data.email || '', phone: data.phone, message: data.message }), deleteInquiry: async id => Boolean(await Inquiry.findByIdAndDelete(id)), getAllEmployees: () => Employee.find().sort({ created_at: -1 }).lean(), createEmployee: data => Employee.create({ name: data.name, role: data.role, phone: data.phone || '', email: data.email || '', status: data.status || 'active' }), deleteEmployee: async id => Boolean(await Employee.findByIdAndDelete(id)) };
